
image_save_iter: 1000
snapshot_save_iter: 10000
log_iter: 10

# optimization options
total_iterations: 310000
batch_size: 8                
num_workers: 1 
weight_decay: 0         
beta1: 0
beta2: 0.99
init: kaiming
lr_dis: 0.0001
lr_gen_mappers: 0.000001
lr_gen_others: 0.0001

# 
adv_w: 3
sty_w: 1                  
rec_w: 2
id_w: 1
style_dim: 256
noise_dim: 32

discriminators:

  channels: [64, 128, 256, 512, 1024, 2048]
extractors:

  channels: [64, 128, 256, 512, 1024, 2048]
encoder:

  channels: [64, 128, 256]
translators:

  channels: [64, 64, 64, 64, 64, 64, 64, 64]
decoder:

  channels: [256, 128, 64]
mappers: 

  pre_channels: [256, 256, 256]
  post_channels: [256, 256, 256]
    
tags:
  -
    name: Male
    tag_irrelevant_conditions_dim: 2
    attributes: 
      -
        name: 'with'
        filename: path-to-Male_with.txt
      -
        name: 'without'
        filename: path-to-Male_without.txt
  -
    name: Young
    tag_irrelevant_conditions_dim: 2
    attributes: 
      -
        name: 'with'
        filename: path-to-Young_with.txt
      -
        name: 'without'
        filename: path-to-Young_without.txt
  -
    name: Smiling
    tag_irrelevant_conditions_dim: 2
    attributes: 
      -
        name: 'with'
        filename: path-to-Smiling_with.txt
      -
        name: 'without'
        filename: path-to-Smiling_without.txt
        

input_dim: 3
new_size: 128
crop_image_height: 128
crop_image_width: 128

